# -*- coding: utf-8 -*-
"""ML-NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvC5WIVmkhFAa8RDxOfCS6ZMiHr37z54
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('train.txt',sep =';',header= None ,names = ['text','emotion'])

df

df.isnull().sum()

unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
    emotion_numbers[emo] = i
    i += 1

df['emotion']  = df['emotion'].map(emotion_numbers)

df

df['text'] = df['text'].apply(lambda x: x.lower())

df

import string
def remove_punc(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df['text']= df['text'].apply(remove_punc)

def remove_numbers(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new += i
  return new

df['text']= df['text'].apply(remove_numbers)

def remove_emojies(txt):
    new = ""
    for i in txt:
      if i.isascii():
         new += i
    return new

df['text']= df['text'].apply(remove_emojies)

import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stop_words = set(stopwords.words('english'))

len(stop_words)

def remove (txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return " ".join(cleaned)

df['text']= df['text'].apply(remove)

df.loc[1]['text']

df

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)

X_test

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
nb = MultinomialNB()
nb.fit(X_train_bow, y_train)

pred_bow = nb.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb2 = MultinomialNB()
nb2.fit(X_train_tfidf, y_train)

pred_tfidf = nb2.predict(X_test_tfidf)
print(accuracy_score(y_test, pred_tfidf))

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_tfidf, y_train)

lr_pred_tfidf = lr.predict(X_test_tfidf)
print(accuracy_score(y_test, lr_pred_tfidf))

from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train_tfidf, y_train)

svm_pred_tfidf = svm.predict(X_test_tfidf)
print(accuracy_score(y_test, svm_pred_tfidf))

from joblib import dump, load

# Save model and vectorizer with .pkl extension
dump(lr, 'emotion_logistic_model.pkl')
dump(tfidf_vectorizer, 'emotion_tfidf_vectorizer.pkl')
dump(emotion_numbers, 'emotion_label_mapping.pkl')  # Optional if you're saving the label map

